# Generated by Django 3.0.4 on 2020-04-01 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200330_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue_model',
            name='affected_user',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.Profile'),
        ),
    ]
